### ISSUE TITLE
Adapt Fellowship plans to accommodate remote conferences

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/ssi-fellowship#14]
This issue is here to collect ideas on how to adapt my Fellowship goals for remote conferences.

**Comment by manics** [comment]
This doesn't really fit in with your original proposal, but I think it'd be cool if there was a way to run a "teaching the teachers" workshop, with the aim of showing people how to effectively run a remote workshop:
- How to use binder/jupyter to teach a remote hands-on workshop.
- What features of binder/jupyter are particularly useful for teachers or students in a remote environment.

**Comment by sgibson91** [comment]
That's a really cool idea! Perhaps @malvikasharan knows of some resources from the Carpentries?

**Comment by malvikasharan** [comment]
We do use online training for train-the-trainer workshop for The carpentries. The idea is that this training should help people teach technical workshops independent of the topic. Here is the training material: https://carpentries.github.io/instructor-training/

We are running one in May, for which registration is currently open: https://mkuzak.github.io/2020-05-19-TtT-online-elixir/

Since both SSI and Turing are partners, we can also think about repeating this if needed (given there is sufficient demand).
